### ISSUE TITLE
script to generate data and augmentation

### ISSUE THREAD

**Issue by chaoyan1037** [pschwllr/MolecularTransformer#1]
Thanks for providing the source code of your model!
I have successfully run your model, but I found the MIT_mixed and MIT_mixed_augm folder contain the same data. Can you also provide the script to generate these data? Appreciated for that.

**Comment by pschwllr** [comment]
Sorry for the late response. I've updated the tokenized MIT_mixed_augm set. 

To generate an augmented set yourself, simply replace the molecules in the input (reactants and reagents) of the MIT_mixed set with random equivalent molecules as described under data augmentation, we also reordered them alphabetically. So the recipe would be:

--> split source string at '.', replace all molecules with random equivalent, reorder them and rejoin them with '.'

**Comment by chaoyan1037** [comment]
Got it! Thanks for your response!
