### ISSUE TITLE
RuntimeError: index_select(): Expected dtype int32 or int64 for index

### ISSUE THREAD

**Issue by val2021-svg** [pschwllr/MolecularTransformer#13]
During the Translation step of the Molecular Transformer code I am facing the following error:

`/usr/local/lib/python3.7/dist-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
Traceback (most recent call last):
  File "/content/gdrive/MolecularTransformer-master/translate.py", line 36, in <module>
    main(opt)
  File "/content/gdrive/MolecularTransformer-master/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/content/gdrive/MolecularTransformer-master/onmt/translate/translator.py", line 235, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/content/gdrive/MolecularTransformer-master/onmt/translate/translator.py", line 342, in translate_batch
    return_attention=self.replace_unk)
  File "/content/gdrive/MolecularTransformer-master/onmt/translate/translator.py", line 470, in _fast_translate_batch
    a= [alive_seq.index_select(0, select_indices),
RuntimeError: index_select(): Expected dtype int32 or int64 for index`

while trying to run the following code:

`model="MIT_mixed_augm_model_augm_model_steo_10000.pt"
!python "/content/gdrive/MolecularTransformer-master/translate.py" 
-model "/content/gdrive/MolecularTransformer-master/experiments/checkpoints/MIT_mixed_augm/MIT_mixed_augm_model_step_10000.pt" \
                    -src "/content/gdrive/MolecularTransformer-master/data/MIT_mixed_augm/src-test.txt" \
                    -output "/content/gdrive/MolecularTransformer-master/experiments/results/predictions_{model}_on_{dataset}_test.txt" \
                    -batch_size 64 -replace_unk -max_length 200 -fast`

I have found another issue (closed) with the same error but the solution of changing the version did not help me here. I am using torch-1.9.0  and torchtext-0.10.0. Are there any updates I should know about? Thank you in advance.

**Comment by pschwllr** [comment]
The models were developed with pytorch 0.4.1 and torchtext 0.3.1. If you want to use our trained models you have to downgrade your torch and torchtext version, as the newer versions are not compatible anymore. 

Or you can use the training data to train your own models with the newer versions.

**Comment by zenwara** [comment]
Hi, I meet the same question recently, how do you solve this promble finally? and I would appreciate it a lot if you share your experience! Thank you in advance.

**Comment by zenwara** [comment]
Hi, I meet the same issue recently, how do you solve this promble finally? and I would appreciate it a lot if you share your experience! Thank you in advance.
