### ISSUE TITLE
how to classify reactions into subclasses?

### ISSUE THREAD

**Issue by Y-H-Joe** [pschwllr/MolecularTransformer#15]
Hi Schwaller,
   I've spent days tackling one issue, the Table5 in your article.
![image](https://user-images.githubusercontent.com/28485220/162326181-c94ed3fb-c36b-4682-926a-cd76bc7814d5.png)

I found everywhere, including your previous work "Found in Translation”: predicting outcomes of complex organic chemistry reactions using neural sequence-to-sequence models", but couldn't figure out how to classify reactions into these subclasses.
I'm pretty sure you guys didn't do it manually.

Could you please give me some help?

Thanks a lot!

**Comment by pschwllr** [comment]
For this, we used pre-classified reactions from the commercially available Pistachio dataset (https://nextmovesoftware.com/pistachio). 

We have done some work on reaction classification in https://github.com/rxn4chemistry/rxnfp, but again most of the reaction classes are from proprietary datasets.
