### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by linminhtoo** [pschwllr/MolecularTransformer#16]
Hello Philippe, 

Just spotted a typo in the README under the data augmentation section:

```
random_equivalent_smiles = Chem.MolFromSmiles(Chem.MolToSmiles(smi, doRandom=True))
```

I believe it should be 
```
random_equivalent_smiles = Chem.MolToSmiles(Chem.MolFromSmiles(smi), doRandom=True)
```

I can create a PR if needed.

Cheers.

**Comment by pschwllr** [comment]
Thanks for pointing it out! I've quickly fixed it. Cheers, Philippe
