### ISSUE TITLE
no model after training

### ISSUE THREAD

**Issue by acquaregia** [pschwllr/MolecularTransformer#2]
Good morning,
 I am replicating training following documentation.
At the end of the training, I do not find the model (average of 20 checkpoints)

-save_model experiments/checkpoints/${dataset}/**${dataset}_model**

should we create the  ${dataset}_model directory beforehand or the software creates it?
even when I create it myself, I do not find there the expected file ${dataset}_model_average_20.pt 

Thanks in advance for your help.
Cheers,
Marco

**Comment by pschwllr** [comment]
This is clearly possible. Best contact me per email: phs[at]zurich.ibm.com.
