### ISSUE TITLE
Extracting features

### ISSUE THREAD

**Issue by Vykintasj** [pschwllr/MolecularTransformer#3]
Hi,
Is there a script/function to extract features from reagents/products or the whole reaction? I can only find the extract_features.py which creates embeddings for every atom in the vocabulary.

Thank you. Best regards,
Vykintas

**Comment by pschwllr** [comment]
Hi, sorry I missed that issue. If you want to extract features from specific part of the reaction or the whole reaction. I would follow our recent work on chemical reaction classification and fingerprints.

Link to paper: https://chemrxiv.org/articles/Data-Driven_Chemical_Reaction_Classification_with_Attention-Based_Neural_Networks/9897365

Best regards,

Philippe
