### ISSUE TITLE
Extraction of Attention Weights

### ISSUE THREAD

**Issue by Sum02dean** [pschwllr/MolecularTransformer#4]
Hello, 

Great tool! I would like to know the best way to store attention weights (for later visualization) for each SMILES string during evaluation. Is there a means to extract this information?

best, 
Dean

**Comment by pschwllr** [comment]
Hi Dean,

Sorry for the late reply. The best way to store the attention is to output it similar to `all_predictions` and `all_scores` in the translator.py.

-> https://github.com/pschwllr/MolecularTransformer/blob/master/onmt/translate/translator.py#L232

I hope this helps.

Best,

Philippe
