### ISSUE TITLE
Error with download data

### ISSUE THREAD

**Issue by shiyu22** [pschwllr/MolecularTransformer#7]
Thanks to your guys to provide such an awesome project.

I have trid to run Training and Testing, but I can't download the tokenized datasets, Models, and results from Box, is it because I am not a part of IBM?

Is there any other link to download data besides Box?

Thanks

**Comment by pschwllr** [comment]
Hi, for me the following link works without an IBM/Box login: https://ibm.ent.box.com/v/MolecularTransformerData

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/38880871/114726792-f988f380-9d3d-11eb-93c7-3c1023c6b62d.png">

Is this the one that you were using?

**Comment by shiyu22** [comment]
Yes, it works. Yesterday it may have been my network problem, the download kept failing, this time it worked.

Thanks anyway.
