### ISSUE TITLE
after running translate.py prediction average scores are negative 

### ISSUE THREAD

**Issue by def123abcxyz** [pschwllr/MolecularTransformer#8]
![Train_validation](https://user-images.githubusercontent.com/83149367/115981170-943fc880-a5af-11eb-8c7e-72485370a332.png)

Kindly let me know what could have gone wrong i am using the pr-trained model and the tokenised dataset  shared.
Thank you  .

**Comment by pschwllr** [comment]
There is nothing with that. The `PRED AVG SCORE` that you see are the average log-likelihoods. 

```
import numpy as np
np.exp(-0.0012)
#outputs 0.9988 <--
```

**Comment by def123abcxyz** [comment]
Thank you for answering. Any insight on why the scores are 0.0 when i compare the score.py for target test and predictions obtained as the output of the model.
![Top5_prodiction_scores](https://user-images.githubusercontent.com/83149367/116877161-32c8cb00-ac3b-11eb-9d1b-e085fd9f9338.png)

**Comment by pschwllr** [comment]
Hard to say from the output. How do the first 10 lines of your predictions file look like? Have you used a beam_size of 5 for making the predictions?

**Comment by def123abcxyz** [comment]
It looked similar. I am sending the predicted set for your reference.
[predictions_MIT_separated_test.txt](https://github.com/pschwllr/MolecularTransformer/files/6414937/predictions_MIT_separated_test.txt)

**Comment by pschwllr** [comment]
It looks like you have only the top-1 in your predictions. When you run `translate.py` make sure to set `-n_best 5` to get 5 outputs (top-1 to top-5) per reaction (the default `n_best` is `1`).

**Comment by def123abcxyz** [comment]
Thank you so much it is working.
